
@refreshToken = {{auth.response.cookies['refreshToken']}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWo5YmZnaTgwMDAxOXpvejBvdDExa2EwIiwiaWF0IjoxNzY2MDQyOTA3LCJleHAiOjE3NjYwNDY1MDd9.CHHPH4BPpLVyrClt-6RDxUAZIbi8KjIsEevhPANQtjA

### 서버 상태 확인
GET {{baseUrl}}/health
Content-Type: application/json

### 로그인
# @name auth
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: rest-client-test

{
  "email": "buyer1@test.com",
  "password": "test1234"
}

### 엑세스 토큰 재발급
# @name auth
POST {{baseUrl}}/api/auth/refresh
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json

### 로그아웃
POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json