@refreshToken = {{auth.response.cookies['refreshToken']}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWo5YmZnaTgwMDAxOXpvejBvdDExa2EwIiwiaWF0IjoxNzY2MDQyOTA3LCJleHAiOjE3NjYwNDY1MDd9.CHHPH4BPpLVyrClt-6RDxUAZIbi8KjIsEevhPANQtjA

### 주문 목록 조회
GET {{baseUrl}}/api/orders?limit=10&page=1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 주문 상세 조회
GET {{baseUrl}}/api/orders/{{orderId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 주문 생성
POST {{baseUrl}}/api/orders
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
	"name": "홍길동",
	"phone": "010-1234-5678",
	"address": "서울시 강남구 예시로 1",
	"orderItems": [
		{
			"productId": "<PRODUCT_ID_1>",
			"sizeId": "<SIZE_ID_1>",
			"quantity": 1
		},
		{
			"productId": "<PRODUCT_ID_2>",
			"sizeId": "<SIZE_ID_2>",
			"quantity": 2
		}
	],
	"usePoint": 0
}
